### ISSUE TITLE
Custom Logging

### ISSUE THREAD

**Issue by jack-douglas** [pulse-framework/pulse#29]
Would be nice to have a custom console logger built in.

So say I wanted to log something I could do collectionName.log('stauts (info, success, error)', 'some other data', { data }, `even more ${data}`) and this would show something like this.
![Image of console log](https://i.notifycdn.me/sba4KiUQ.png)

Would be much cleaner than 
![Image of console log 2](https://i.notifycdn.me/DOkyGgG6.png)

It would also be nice if you were able to define the styles of this console log say in the base collection or something like that.

**Comment by TimothyCole** [comment]
Use this :slightly_smiling_face: https://gist.github.com/TimothyCole/edae3c4b01e0b3e3c165ba1b7380fe66
