### ISSUE TITLE
Need a CONTRIBUTING.md

### ISSUE THREAD

**Issue by Snipey** [pulse-framework/pulse#42]
We have no way of knowing what or how to contribute to the current version of pulse as it is listed nowhere on the repo.
## Expected Behavior

People to have a clear cut way of figuring out how to contribute to the framework
## Current Behavior

There is no documentation showing how to contribute

**Comment by NathanielPather** [comment]
Is anybody working on this?

**Comment by Snipey** [comment]
I believe that there will be a section in the documentation for this.
