### ISSUE TITLE
Error on Importing Nested Object with Arrays as Values

### ISSUE THREAD

**Issue by Pckool** [pulse-framework/pulse#53]
When importing an object which has a deep nested object with arrays as values into the data attribute of a collection, it throws an error. 
## Expected Behavior

The object  should have peen imported properly and not have thrown an error when trying to spread it into a pulse collection data attribute.
## Current Behavior

throws this error:
```javascript
pulse.esm.min.js:1056 Uncaught TypeError: Cannot read property 'locations' of undefined
    at t.value (pulse.esm.min.js:1056)
    at t.value (pulse.esm.min.js:1084)
    at Object.set (pulse.esm.min.js:678)
    at e (pulse.esm.min.js:769)
    at e (pulse.esm.min.js:780)
    at t.value (pulse.esm.min.js:781)
    at eval (pulse.esm.min.js:548)
    at Array.forEach (<anonymous>)
    at t.value (pulse.esm.min.js:547)
    at new t (pulse.esm.min.js:466)
```
and does not let vue render at all.
## Extra Information

[Link to example](https://gist.github.com/Pckool/526b619d46c76c6653f724e100bf89c5)
Please check above for an example on the structure and source of the issue.

## Environment Information
- Operating System: `Windows 10 x64 November 2019 Update (H219)`
- Browser Version (If applicable): `Edge (chromium), Firefox Quantum, and Google Chrome`
- Pulse Version: `latest (2.0.3)`
- Framework/Framework Version (If applicable): `vue`

**Comment by Pckool** [comment]
Figured out this only occurs when using the `new Pulse.Library()` constructor. Fixed when using the `new Pulse()` constructor

**Comment by jamiepine** [comment]
Sorry about this. Pulse 2.2 is about to be released which should be much more stable with clear documentation!

**Comment by Pckool** [comment]
Not a problem! Looking forward to 2.2, keep up the good work!
Closing the thread.
